name: CI & CD
on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    env:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: GitHub Action for Yarn
      uses: Borales/actions-yarn@v2.0.1
    - name: yarn install, build, and test
      run: |
        yarn install --cwd functions
        yarn lint
        yarn tsc
    - name: Deploy
      if: github.ref == 'refs/heads/master'
      run: |  
        yarn semantic-release
      env:
        CI: true
